# Generated by Django 4.2.2 on 2023-07-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_profile_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
