# Generated by Django 4.2.2 on 2023-07-28 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='address2',
        ),
    ]
