# Generated by Django 4.2.2 on 2023-07-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
