# Generated by Django 4.2.2 on 2023-07-21 08:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_availablecolors_availablesizes_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecolors',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
