# Generated by Django 4.2.2 on 2023-07-21 08:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_availablecolors_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecolors',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
