# Generated by Django 4.2.2 on 2023-07-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_availablecolors_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecolors',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
