# Generated by Django 4.2.2 on 2023-07-21 09:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_name_availablecolors_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecolors',
            name='hexcolor',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=7, samples=None),
        ),
    ]
