# Generated by Django 4.2.2 on 2023-07-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_availablecolors_hexcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablesizes',
            name='size',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
