# Generated by Django 4.2.2 on 2023-08-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_image_url_product_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablesizes',
            options={'ordering': ['expressed_in']},
        ),
        migrations.AlterField(
            model_name='availablesizes',
            name='expressed_in',
            field=models.CharField(choices=[('infants', 'infants'), ('shoes', 'shoes'), ('standard', 'standard'), ('universal', 'universal')], max_length=9),
        ),
        migrations.AlterField(
            model_name='availablesizes',
            name='size',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
