# Generated by Django 4.2.2 on 2023-08-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_availablesizes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablesizes',
            options={'ordering': ['size']},
        ),
        migrations.RemoveField(
            model_name='availablesizes',
            name='expressed_in',
        ),
        migrations.AlterField(
            model_name='availablesizes',
            name='size',
            field=models.CharField(choices=[('XS', 'XS_standard'), ('S', 'S_standard'), ('M', 'M_standard'), ('L', 'L_standard'), ('XL', 'XL_standard'), ('0-6', '0-6_infant'), ('6-12', '6-12_infant'), ('12-18', '12-18_infant'), ('18-24', '18-24_infant'), ('2-4', '2-4_infant'), ('24-30', '24-30_shoe'), ('30-35', '30-35_shoe'), ('35-38', '35-38_shoe'), ('38-43', '38-43_shoe')], max_length=5, unique=True),
        ),
    ]
