# Generated by Django 4.2.4 on 2023-08-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_availablecolor_rename_availablesizes_availablesize_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableColors',
        ),
    ]
